export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INCREASE_COUNT_IN_STOCK = 'INCREASE_COUNT_IN_STOCK';
export const REDUCE_COUNT_IN_STOCK = 'REDUCE_COUNT_IN_STOCK';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const REDUCE_PRODUCT_FROM_CART = 'REDUCE_PRODUCT_FROM_CART';
export const INCREASE_PRODUCT_FROM_CART = 'INCREASE_PRODUCT_FROM_CART';